### ISSUE TITLE
ibatis-spring jar download

### ISSUE THREAD

**Issue by clockwiser** [mybatis/ibatis-spring#32]
Is there jar file downladable for ibatis-spring?

**Comment by harawata** [comment]
There is a link to the `jar` for each version : https://repo1.maven.org/maven2/org/mybatis/mybatis-2-spring/

**Comment by clockwiser** [comment]
> There is a link to the `jar` for each version : https://repo1.maven.org/maven2/org/mybatis/mybatis-2-spring/

Thanks!
